// source: cpg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cpg.AdditionalEdgeProperty');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.cpg.CpgStruct.Edge.Property');

goog.forwardDeclare('proto.cpg.CpgStruct.Edge.EdgeType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cpg.AdditionalEdgeProperty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cpg.AdditionalEdgeProperty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cpg.AdditionalEdgeProperty.displayName = 'proto.cpg.AdditionalEdgeProperty';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cpg.AdditionalEdgeProperty.prototype.toObject = function(opt_includeInstance) {
  return proto.cpg.AdditionalEdgeProperty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cpg.AdditionalEdgeProperty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cpg.AdditionalEdgeProperty.toObject = function(includeInstance, msg) {
  var f, obj = {
    edgeId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    property: (f = msg.getProperty()) && proto.cpg.CpgStruct.Edge.Property.toObject(includeInstance, f),
    outNodeKey: jspb.Message.getFieldWithDefault(msg, 3, 0),
    inNodeKey: jspb.Message.getFieldWithDefault(msg, 4, 0),
    edgeType: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cpg.AdditionalEdgeProperty}
 */
proto.cpg.AdditionalEdgeProperty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cpg.AdditionalEdgeProperty;
  return proto.cpg.AdditionalEdgeProperty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cpg.AdditionalEdgeProperty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cpg.AdditionalEdgeProperty}
 */
proto.cpg.AdditionalEdgeProperty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEdgeId(value);
      break;
    case 2:
      var value = new proto.cpg.CpgStruct.Edge.Property;
      reader.readMessage(value,proto.cpg.CpgStruct.Edge.Property.deserializeBinaryFromReader);
      msg.setProperty(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setOutNodeKey(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInNodeKey(value);
      break;
    case 5:
      var value = /** @type {!proto.cpg.CpgStruct.Edge.EdgeType} */ (reader.readEnum());
      msg.setEdgeType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cpg.AdditionalEdgeProperty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cpg.AdditionalEdgeProperty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cpg.AdditionalEdgeProperty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cpg.AdditionalEdgeProperty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEdgeId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getProperty();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cpg.CpgStruct.Edge.Property.serializeBinaryToWriter
    );
  }
  f = message.getOutNodeKey();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getInNodeKey();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getEdgeType();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional int64 edge_id = 1;
 * @return {number}
 */
proto.cpg.AdditionalEdgeProperty.prototype.getEdgeId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cpg.AdditionalEdgeProperty} returns this
 */
proto.cpg.AdditionalEdgeProperty.prototype.setEdgeId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional CpgStruct.Edge.Property property = 2;
 * @return {?proto.cpg.CpgStruct.Edge.Property}
 */
proto.cpg.AdditionalEdgeProperty.prototype.getProperty = function() {
  return /** @type{?proto.cpg.CpgStruct.Edge.Property} */ (
    jspb.Message.getWrapperField(this, proto.cpg.CpgStruct.Edge.Property, 2));
};


/**
 * @param {?proto.cpg.CpgStruct.Edge.Property|undefined} value
 * @return {!proto.cpg.AdditionalEdgeProperty} returns this
*/
proto.cpg.AdditionalEdgeProperty.prototype.setProperty = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cpg.AdditionalEdgeProperty} returns this
 */
proto.cpg.AdditionalEdgeProperty.prototype.clearProperty = function() {
  return this.setProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cpg.AdditionalEdgeProperty.prototype.hasProperty = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 out_node_key = 3;
 * @return {number}
 */
proto.cpg.AdditionalEdgeProperty.prototype.getOutNodeKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.cpg.AdditionalEdgeProperty} returns this
 */
proto.cpg.AdditionalEdgeProperty.prototype.setOutNodeKey = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 in_node_key = 4;
 * @return {number}
 */
proto.cpg.AdditionalEdgeProperty.prototype.getInNodeKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cpg.AdditionalEdgeProperty} returns this
 */
proto.cpg.AdditionalEdgeProperty.prototype.setInNodeKey = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional CpgStruct.Edge.EdgeType edge_type = 5;
 * @return {!proto.cpg.CpgStruct.Edge.EdgeType}
 */
proto.cpg.AdditionalEdgeProperty.prototype.getEdgeType = function() {
  return /** @type {!proto.cpg.CpgStruct.Edge.EdgeType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.cpg.CpgStruct.Edge.EdgeType} value
 * @return {!proto.cpg.AdditionalEdgeProperty} returns this
 */
proto.cpg.AdditionalEdgeProperty.prototype.setEdgeType = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


