// source: cpg.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.cpg.NodePropertyName');

/**
 * @enum {number}
 */
proto.cpg.NodePropertyName = {
  UNKNOWN_NODE_PROPERTY: 0,
  LINE_NUMBER: 2,
  PARSER_TYPE_NAME: 3,
  ORDER: 4,
  NAME: 5,
  FULL_NAME: 6,
  IS_EXTERNAL: 7,
  VALUE: 8,
  COLUMN_NUMBER: 11,
  LINE_NUMBER_END: 12,
  VERSION: 13,
  BINARY_SIGNATURE: 14,
  EVALUATION_STRATEGY: 15,
  COLUMN_NUMBER_END: 16,
  DEPTH_FIRST_ORDER: 17,
  LANGUAGE: 19,
  CONTENT: 20,
  CODE: 21,
  SIGNATURE: 22,
  HAS_MAPPING: 23,
  RESOLVED: 24,
  DISPATCH_TYPE: 25,
  MODIFIER_TYPE: 26,
  CONTROL_STRUCTURE_TYPE: 27,
  ARGUMENT_INDEX: 40,
  CLOSURE_BINDING_ID: 50,
  TYPE_FULL_NAME: 51,
  TYPE_DECL_FULL_NAME: 52,
  INHERITS_FROM_TYPE_FULL_NAME: 53,
  METHOD_FULL_NAME: 54,
  METHOD_INST_FULL_NAME: 55,
  AST_PARENT_TYPE: 56,
  AST_PARENT_FULL_NAME: 57,
  DEPENDENCY_GROUP_ID: 58,
  INTERNAL_FLAGS: 78,
  SYMBOL: 100,
  METHOD_SHORT_NAME: 102,
  PACKAGE_NAME: 103,
  CLASS_NAME: 104,
  NODE_LABEL: 105,
  FILENAME: 106,
  ANNOTATION_NAME: 107,
  ANNOTATION_FULL_NAME: 108,
  IS_STATIC: 110,
  VAR_TYPE: 111,
  EVALUATION_TYPE: 112,
  PARAMETER_INDEX: 113,
  FINGERPRINT: 114,
  SOURCE_TYPE: 115,
  SINK_TYPE: 116,
  CATEGORY: 117,
  OVERLAYS: 118,
  POLICY_DIRECTORIES: 119,
  HASH: 120,
  PATH: 121,
  SPID: 122,
  LITERALS_TO_SINK: 123,
  ARGUMENT_NAME: 130,
  KEY: 131,
  CLASS_SHORT_NAME: 132,
  ALIAS_TYPE_FULL_NAME: 158,
  CLOSURE_ORIGINAL_NAME: 159,
  IS_VARIADIC: 221,
  VARARG_PARAMETER: 222,
  PATTERN: 813,
  CATEGORIES: 814,
  EVAL_TYPE: 815,
  IS_METHOD_NEVER_OVERRIDDEN: 1002,
  DYNAMIC_TYPE_HINT_FULL_NAME: 1591,
  STRUCTURED_FINGERPRINT: 1714,
  USED_IN: 22919,
  CANONICAL_NAME: 2001092,
  CONTAINED_REF: 2007161
};

